### ISSUE TITLE
Test Module Locations

### ISSUE THREAD

**Issue by pboyer** [chilts/awssum-amazon-cloudsearch#3]
I needed to use:

``` javascript
var awssum = require('awssum');
var SearchService = awssum.load('../awssum-amazon-cloudsearch/awssum-amazon-cloudsearch').SearchService;
var DocumentService = awssum.load('../awssum-amazon-cloudsearch/awssum-amazon-cloudsearch').DocumentService;
var CloudSearch = awssum.load('../awssum-amazon-cloudsearch/awssum-amazon-cloudsearch').CloudSearch;
```

in order to use this module.  I found the require mechanism shown in the test file to result in module loading errors in Node 0.8.20.

Thanks for your awesome project.

~Peter

**Comment by chilts** [comment]
Hi Peter,

I think you have a bit of a mix there before v0.12 (single immense AwsSum) and v1.0.0 (smaller pluggable AwsSum).

I'll go have a try and come back to you with a better way, since with the new AwsSum you won't need a lot of that boilerplate. :)

Hold one tick until I get time at lunch to get back to you. :)

Cheers,
Andy

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
